Freelancer/Models/Search/SearchRequestModel.cs
namespace Freelancer.Models.Search;

public class SearchRequestModel
{
    public string? Query { get; set; }
    public int Page { get; set; }
    public int PageSize { get; set; }
    public int Skip => Page > 1 ? (Page - 1) * PageSize : 0;

    public SearchRequestModel(string? query, string? page, int pageSize)
    {
        Query = query;

        if (int.TryParse(page, out int pageNumber) && pageNumber > 0)
        {
            Page = pageNumber;
        }

        PageSize = pageSize;
    }
}

Freelancer/Models/Search/SearchResponseModel.cs
using Examine;

namespace Freelancer.Models.Search;

public class SearchResponseModel
{
    public bool HasResults => TotalResultCount > 0;
    public string? Query { get; set; }
    public long TotalResultCount { get; set; }
    public IEnumerable<ISearchResult>? SearchResults { get; set; }

    public SearchResponseModel() { }

    public SearchResponseModel(string? query, long totalResultCount, IEnumerable<ISearchResult>? searchResults)
    {
        Query = query;
        TotalResultCount = totalResultCount;
        SearchResults = searchResults;
    }
}

Freelancer/Models/ViewModels/ContactViewModel.cs
using System.ComponentModel.DataAnnotations;

using Freelancer.Validation;

namespace Freelancer.Models.ViewModels;

public class ContactViewModel
{
    [Display(Name = "Full name")]
    [Required(ErrorMessage = "You must enter your name")]
    public string? Name { get; set; }

    [Display(Name = "Email address")]
    [EmailAddress(ErrorMessage = "You must enter a valid email address")]
    [Required(ErrorMessage = "You must enter your email address")]
    public string? Email { get; set; }

    [Display(Name = "Phone number")]
    public string? Phone { get; set; }

    [Display(Name = "Message")]
    [Required(ErrorMessage = "You must enter your message")]
    public string? Message { get; set; }

    [Display(Name = "Yes, I give permission to store and process my data")]
    [Required(ErrorMessage = "You must give consent to us storing your details before you can send us a message")]
    [MustBeTrue(ErrorMessage = "You must give consent to us storing your details before you can send us a message")]
    public bool Consent { get; set; }
}

Freelancer/Components/ContactViewComponent.cs
using Freelancer.Models.ViewModels;

using Microsoft.AspNetCore.Mvc;

namespace Freelancer.Components;

[ViewComponent(Name = "Contact")]
public class ContactViewComponent : ViewComponent
{
    public IViewComponentResult Invoke(ContactViewModel model)
    {
        model ??= new ContactViewModel();

        return View(model);
    }
}

Freelancer/Components/SearchFormViewComponent.cs
using Freelancer.Models.ViewModels;

using Microsoft.AspNetCore.Mvc;

namespace Freelancer.Components;

[ViewComponent(Name = "Contact")]
public class ContactViewComponent : ViewComponent
{
    public IViewComponentResult Invoke(ContactViewModel model)
    {
        model ??= new ContactViewModel();

        return View(model);
    }
}

Freelancer/Controllers/Surface/ContactSurfaceController.cs
using Freelancer.Configuration;
using Freelancer.Models.ViewModels;

using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

using Umbraco.Cms.Core.Cache;
using Umbraco.Cms.Core.Logging;
using Umbraco.Cms.Core.Mail;
using Umbraco.Cms.Core.Models.Email;
using Umbraco.Cms.Core.Routing;
using Umbraco.Cms.Core.Services;
using Umbraco.Cms.Core.Web;
using Umbraco.Cms.Infrastructure.Persistence;
using Umbraco.Cms.Web.Website.Controllers;

namespace Freelancer.Controllers.Surface;

public class ContactSurfaceController : SurfaceController
{
    private readonly IEmailSender _emailSender;
    private readonly ILogger<ContactSurfaceController> _logger;
    private readonly FreelancerConfig _freelancerConfig;

    public ContactSurfaceController(
        IUmbracoContextAccessor umbracoContextAccessor,
        IUmbracoDatabaseFactory databaseFactory,
        ServiceContext services,
        AppCaches appCaches,
        IProfilingLogger profilingLogger,
        IPublishedUrlProvider publishedUrlProvider,
        IEmailSender emailSender,
        ILogger<ContactSurfaceController> logger,
        IOptions<FreelancerConfig> freelancerConfig) : base(umbracoContextAccessor, databaseFactory, services, appCaches, profilingLogger, publishedUrlProvider)
    {
        _emailSender = emailSender;
        _logger = logger;
        _freelancerConfig = freelancerConfig.Value;
    }

    public async Task<IActionResult> Submit(ContactViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return CurrentUmbracoPage();
        }

        try
        {
            var subject = string.Format("Enquiry from: {0} - {1}", model.Name, model.Email);
            EmailMessage message = new(_freelancerConfig?.EmailSettings?.From,
                _freelancerConfig?.EmailSettings?.To, subject, model.Message, false);
            await _emailSender.SendAsync(message, emailType: "Contact");

            TempData["ContactSuccess"] = true;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Contact Form Submission Error");
            TempData["ContactSuccess"] = false;
        }

        return RedirectToCurrentUmbracoPage();
    }
}

Freelancer/Views/Partials/about.cshtml
<!-- About Section-->
<section class="page-section bg-primary text-white mb-0" id="about">
    <div class="container">
        <!-- About Section Heading-->
        <h2 class="page-section-heading text-center text-uppercase text-white">About</h2>
        <!-- Icon Divider-->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon">
                <i class="fas fa-star"></i>
            </div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- About Section Content-->
        <div class="row">
            <div class="col-lg-4 ms-auto">
                <p class="lead">Freelancer is a free bootstrap theme created by Start Bootstrap. The download includes the complete source files including HTML, CSS, and JavaScript as well as optional SASS stylesheets for easy customization.</p>
            </div>
            <div class="col-lg-4 me-auto">
                <p class="lead">You can create your own custom avatar for the masthead, change the icon in the dividers, and add your email address to the contact form to make it fully functional!</p>
            </div>
        </div>
        <!-- About Section Button-->
        <div class="text-center mt-4">
            <a class="btn btn-xl btn-outline-light" href="https://startbootstrap.com/theme/freelancer/">
                <i class="fas fa-download me-2"></i>
                Free Download!
            </a>
        </div>
    </div>
</section>

Freelancer/Views/Partials/blockgrid/Components/callToAction.cshtml
@using Umbraco.Cms.Web.Common.PublishedModels
@inherits UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockGridItem<ContentModels.CallToAction>>

@{
    const int TITLE_AREA = 0;
    const int CONTENT_AREA = 1;
    const int LINK_AREA = 2;
    ViewData["hasContainer"] = "true";
}

<section class="page-section bg-primary text-white mb-0" id="about">
    <div class="container">
        <div class="text-white">
            <!-- About Section Heading-->
            @await Html.GetBlockGridItemAreaHtmlAsync(Model.Areas.ElementAt(TITLE_AREA))
        </div>
        <!-- About Section Content-->
        <div class="row">
            @{
                var contentArea = Model.Areas.ElementAt(CONTENT_AREA);
                if(contentArea != null && contentArea.Any())
                {
                    var classToApply = "";
                    var itemCount = contentArea.Count;
                    var i = 0;
                    foreach(var item in contentArea)
                    {
                        if(itemCount > 1)
                        {
                            if(itemCount > 1 && i % 2 == 1)
                            {
                                classToApply = "me-auto";
                            }
                            else
                            {
                                classToApply = "ms-auto";
                            }
                        }
                        else
                        {
                            classToApply = "mx-auto";
                        }

                        <div class="col-lg-@item.ColumnSpan @(classToApply)">
                            @await Html.PartialAsync("blockgrid/Components/richText", item)
                        </div>
                        i++;
                    }
                }
            }
        </div>

        @{
            var linkArea = Model.Areas.ElementAt(LINK_AREA);
        }

        @if(linkArea != null && linkArea.Any())
        {
            foreach(var item in linkArea)
            {
                var iconLink = item.Content as IconLink;
                if(iconLink != null)
                {
                    <!-- About Section Button-->
                    <div class="text-center mt-4">
                        <a class="btn btn-xl btn-outline-light" href="@iconLink.Link.Url" target="@iconLink.Link.Target">
                            @* <i class="fas fa-download me-2"></i> *@
                            <span class="icon-link">
                                <our-svg media-item="iconLink.Icon" class="svg-inline--fa fa-fw text-white"></our-svg>
                            </span>
                            @iconLink.Link.Name
                        </a>
                    </div>
                }
            }
        }

    </div>
</section>

Freelancer/Views/Partials/blockgrid/Components/footerContent.cshtml
@inherits UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockGridItem<ContentModels.FooterContent>>

<h4 class="text-uppercase mb-4">@Model.Content.Title</h4>
@Model.Content.Text

Freelancer/Views/Partials/blockgrid/Components/form.cshtml
@inherits UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockGridItem<ContentModels.Form>>

<!-- Contact Section-->
<section class="page-section" id="contact">
    <div class="container">
        <!-- Contact Section Heading-->
        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Contact Me</h2>
        <!-- Icon Divider-->
        <div class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><svg style="width: 1.2em; height: 1.2em;" class="svg-inline--fa fa-star" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="star" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512" data-fa-i2svg=""><path fill="currentColor" d="M316.9 18C311.6 7 300.4 0 288.1 0s-23.4 7-28.8 18L195 150.3 51.4 171.5c-12 1.8-22 10.2-25.7 21.7s-.7 24.2 7.9 32.7L137.8 329 113.2 474.7c-2 12 3 24.2 12.9 31.3s23 8 33.8 2.3l128.3-68.5 128.3 68.5c10.8 5.7 23.9 4.9 33.8-2.3s14.9-19.3 12.9-31.3L438.5 329 542.7 225.9c8.6-8.5 11.7-21.2 7.9-32.7s-13.7-19.9-25.7-21.7L381.2 150.3 316.9 18z"></path></svg></div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- Contact Section Form-->
        <div class="row justify-content-center">
            <div class="col-lg-8 col-xl-7">
                @await Component.InvokeAsync("Contact")
            </div>
        </div>
    </div>
</section>

Freelancer/Views/Partials/blockgrid/Components/imageLink.cshtml
@inherits UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockGridItem<ContentModels.ImageLink>>

@{
    if (Model?.Content?.Image == null || Model?.Content?.Link == null) return;
}

<!-- Portfolio Item 1-->
<div class="col-md-6 col-lg-4 mb-5">
    <div class="portfolio-item mx-auto">
        <a href="@Model.Content.Link.Url" target="@Model.Content.Link.Target" title="@Model.Content.Link.Name">
            <div class="portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100">
                <div class="portfolio-item-caption-content text-center text-white"><i class="fas fa-plus fa-3x"></i></div>
            </div>
            <img class="img-fluid lazyload" data-srcset="@Url.GetSrcSetUrls(Model.Content.Image, 400, 290)" src="@Model.Content.Image.GetCropUrl(40, 29, quality: 40)" alt="@Model.Content.Image.GetAltText()" width="400" height="290" sizes="auto" />
        </a>
    </div>
</div>

Freelancer/Views/Partials/blockgrid/Components/imageLinks.cshtml
@inherits UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockGridItem<ContentModels.ImageLinks>>

@{
    const int TITLE_AREA = 0;
    const int CONTENT_AREA = 1;
}

<!-- Portfolio Section-->
<section class="page-section portfolio" id="portfolio">
    <div class="container">
        @await Html.GetBlockGridItemAreaHtmlAsync(Model.Areas.ElementAt(TITLE_AREA))
        <!-- Portfolio Grid Items-->
        <div class="row justify-content-center">
            @await Html.GetBlockGridItemAreaHtmlAsync(Model.Areas.ElementAt(CONTENT_AREA))
        </div>
    </div>
</section>

Freelancer/Views/Partials/blockgrid/Components/imageWithCaption.cshtml
@inherits UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockGridItem<ContentModels.ImageWithCaption>>
@using Umbraco.Community.BlockPreview.Extensions

@if (Model?.Content?.Image == null) {return;}

<section class="page-section bg-white text-white mb-0">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto">
                @if(Context.Request.IsBlockPreviewRequest())
                {
                    <img class="img-fluid" src="@Model.Content.Image.GetCropUrl(800, 580)" alt="@Model.Content.Image.GetAltText()" width="800" height="580" />
                }
                else
                {
                    <img class="img-fluid lazyload" data-srcset="@Url.GetSrcSetUrls(Model.Content.Image, 800, 580)" src="@Model.Content.Image.GetCropUrl(80, 58, quality: 40)" alt="@Model.Content.Image.GetAltText()" width="800" height="580" sizes="auto" />
                }
                <p class="text-dark text-center fst-italic">@Model.Content.Caption</p>
            </div>
        </div>
    </div>
</section>

Freelancer/Views/Partials/blockgrid/Components/navigationArea.cshtml
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockGridItem>

@{
    if (Model?.Areas.Any() != true) { return; }
}

@foreach(var area in Model.Areas)
{
    @await Html.GetBlockGridItemAreaHtmlAsync(area)
}

Freelancer/Views/Partials/blockgrid/Components/navigationGroup.cshtml
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockGridItem<ContentModels.NavigationGroup>>

@if ((Model.Content.ChildLinks != null && Model.Content.ChildLinks.Any())
             && (!string.IsNullOrWhiteSpace(Model.Content.Title) || Model.Content.Link != null))
{
    <li class="nav-item mx-0 mx-lg-1 dropdown">
        @if(Model.Content.Link != null)
        {
            <a class="nav-link py-3 px-0 px-lg-3 rounded dropdown-toggle" target="@Model.Content.Link.Target" href="@Model.Content.Link.Url" id="@Model.Content.Key.ToString("N")" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                @Model.Content.Link.Name
            </a>
        }
        else if(!string.IsNullOrWhiteSpace(Model.Content.Title))
        {
            <a class="nav-link py-3 px-0 px-lg-3 rounded dropdown-toggle" href="#" id="@Model.Content.Key.ToString("N")" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                @Model.Content.Title
            </a>
        }
        <ul class="dropdown-menu" aria-labelledby="@Model.Content.Key.ToString("N")">
            @foreach(var childLink in Model.Content.ChildLinks)
            {
                <li><a class="dropdown-item" target="@childLink.Target" href="@childLink.Url">@childLink.Name</a></li>
            }
        </ul>
    </li>
}
else
{
    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" target="@Model.Content.Link.Target" href="@Model.Content.Link.Url">@Model.Content.Link.Name</a></li>
}

Freelancer/Views/Partials/blockgrid/Components/reusableContent.cshtml
@inherits UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockGridItem<ContentModels.ReusableContent>>

@{
    if (Model?.Content?.ContentItem is null) return;
}

@await Html.GetBlockGridHtmlAsync(Model.Content.ContentItem, "mainContent")

Freelancer/Views/Partials/blockgrid/Components/richText.cshtml
@inherits UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockGridItem<ContentModels.RichText>>

@{
    var hasContainer = ViewData["hasContainer"] == "true";
}

@if(hasContainer)
{
    @Model.Content.Text
}
else
{
    <div class="container my-5">
        <div class="col-lg-8 mx-auto">
            @Model.Content.Text
        </div>
    </div>
}

Freelancer/Views/Partials/blockgrid/Components/socialLinks.cshtml
@using Umbraco.Cms.Core.Models.Blocks
@inherits UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockGridItem<ContentModels.SocialLinks>>

<h4 class="text-uppercase mb-4">@Model.Content.Title</h4>

@if(Model.Content?.Links?.Count > 0)
{
    foreach(BlockListItem<ContentModels.SocialLink> item in Model.Content.Links)
    {
        if (item.Content.Link is null || item.Content.Icon is null 
            || item.Content.IconColor is null || item.Content.InverterdIconColor is null) continue;

        var iconKey = item.Content.Icon.Key.ToString("N");
        
        <style>
            .svg-@iconKey {
                fill:@($"#{item.Content.IconColor.Color}");
            }
            .svg-@iconKey:hover, .svg-@iconKey:focus {
                fill:@($"#{item.Content.InverterdIconColor.Color}");
            }
        </style>
        
        <a class="btn btn-outline-light btn-social mx-1 svg-@iconKey" href="@item.Content.Link.Url" title="@item.Content.Link.Name" target="@item.Content.Link.Target">
            <our-svg media-item="item.Content.Icon" class="svg-inline--fa fa-fw"></our-svg>
        </a>
    }
}

Freelancer/Views/Partials/blockgrid/Components/standardHeader.cshtml
@using Freelancer.Extensions
@inherits UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockGridItem<ContentModels.StandardHeader>>

<header class="masthead bg-primary text-white text-center">
    <div class="container d-flex align-items-center flex-column">
        @if(Model.Content.Image != null)
        {
            <!-- Masthead Avatar Image-->
            <img class="masthead-avatar mb-5" src="@Model.Content.Image.GetCropUrl(240)" alt="@Model.Content.Image.GetAltText()" />
        }
        <!-- Masthead Heading-->
        <h1 class="masthead-heading text-uppercase mb-0">@Model.Content.Title</h1>

        @if(!string.IsNullOrWhiteSpace(Model.Content.Subtitle))
        {
            <!-- Icon Divider-->
            <div class="divider-custom divider-light">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                <div class="divider-custom-line"></div>
            </div>
            <!-- Masthead Subheading-->
            <p class="masthead-subheading font-weight-light mb-0">@Model.Content.Subtitle</p>
        }
    </div>
</header>

Freelancer/Views/Partials/blockgrid/Components/threeColumn.cshtml
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockGridItem>

@{
    if (Model?.Areas.Any() != true) { return; }
}

@foreach(var area in Model.Areas)
{
    <div class="col-lg-4 mb-5 mb-lg-0">
        @await Html.GetBlockGridItemAreaHtmlAsync(area)
    </div>
}

Freelancer/Views/Partials/blockgrid/Components/title.cshtml
@inherits UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockGridItem<ContentModels.Title>>

@{
    var textColourClass = Model.Content.Color != null ? "text-" + Model.Content.Color.Label.ToLower() : "text-secondary";
    var dividerColourClass = Model.Content.Color != null && Model.Content.Color.Label == "White" ? "divider-light" : null;
}

<!-- Portfolio Section Heading-->
<h2 class="page-section-heading text-center text-uppercase @(textColourClass) mb-0">@Model.Content.Text</h2>
<!-- Icon Divider-->
<div class="divider-custom @(dividerColourClass)">
    <div class="divider-custom-line"></div>
    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
    <div class="divider-custom-line"></div>
</div>

Freelancer/Views/Partials/blockgrid/area.cshtml
@using Umbraco.Extensions
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockGridArea>

@await Html.GetBlockGridItemsHtmlAsync(Model)

Freelancer/Views/Partials/blockgrid/areas.cshtml
@using Umbraco.Extensions
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockGridItem>
@{
    if (Model?.Areas.Any() != true)
    {
        return;
    }
}

@foreach (var area in Model.Areas)
{
    @await Html.GetBlockGridItemAreaHtmlAsync(area)
}

Freelancer/Views/Partials/blockgrid/default.cshtml
@using Umbraco.Extensions
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockGridModel>
@{
    if (Model?.Any() != true)
    {
        return;
    }
}

@await Html.GetBlockGridItemsHtmlAsync(Model)

Freelancer/Views/Partials/blockgrid/items.cshtml
@using Umbraco.Cms.Core.Models.Blocks
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<IEnumerable<BlockGridItem>>
@{
    if (Model?.Any() != true) { return; }
}

@foreach (var item in Model)
{
    var partialViewName = "blockgrid/Components/" + item.Content.ContentType.Alias;
    try
    {
        @await Html.PartialAsync(partialViewName, item)
    }
    catch (InvalidOperationException)
    {
        <p>
            <strong>Could not render component of type: @(item.Content.ContentType.Alias)</strong>
            <br />
            This likely happened because the partial view <em>@partialViewName</em> could not be found.
        </p>
    }
}

Freelancer/Views/Partials/blocklist/default.cshtml
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<Umbraco.Cms.Core.Models.Blocks.BlockListModel>
@{
    if (Model?.Any() != true) { return; }
}
<div class="umb-block-list">
    @foreach (var block in Model)
    {
        if (block?.ContentUdi == null) { continue; }
        var data = block.Content;

        @await Html.PartialAsync("blocklist/Components/" + data.ContentType.Alias, block)
    }
</div>

Freelancer/Views/Partials/contact.cshtml
<!-- Contact Section-->
<section class="page-section" id="contact">
    <div class="container">
        <!-- Contact Section Heading-->
        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Contact Me</h2>
        <!-- Icon Divider-->
        <div class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon">
                <i class="fas fa-star"></i>
            </div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- Contact Section Form-->
        <div class="row justify-content-center">
            <div class="col-lg-8 col-xl-7">
                <!-- * * * * * * * * * * * * * * *-->
                <!-- * * SB Forms Contact Form * *-->
                <!-- * * * * * * * * * * * * * * *-->
                <!-- This form is pre-integrated with SB Forms.-->
                <!-- To make this form functional, sign up at-->
                <!-- https://startbootstrap.com/solution/contact-forms-->
                <!-- to get an API token!-->
                <form id="contactForm" data-sb-form-api-token="API_TOKEN">
                    <!-- Name input-->
                    <div class="form-floating mb-3">
                        <input class="form-control" id="name" type="text" placeholder="Enter your name..." data-sb-validations="required"/>
                        <label for="name">Full name</label>
                        <div class="invalid-feedback" data-sb-feedback="name:required">A name is required.</div>
                    </div>
                    <!-- Email address input-->
                    <div class="form-floating mb-3">
                        <input class="form-control" id="email" type="email" placeholder="name@example.com" data-sb-validations="required,email"/>
                        <label for="email">Email address</label>
                        <div class="invalid-feedback" data-sb-feedback="email:required">An email is required.</div>
                        <div class="invalid-feedback" data-sb-feedback="email:email">Email is not valid.</div>
                    </div>
                    <!-- Phone number input-->
                    <div class="form-floating mb-3">
                        <input class="form-control" id="phone" type="tel" placeholder="(123) 456-7890" data-sb-validations="required"/>
                        <label for="phone">Phone number</label>
                        <div class="invalid-feedback" data-sb-feedback="phone:required">A phone number is required.</div>
                    </div>
                    <!-- Message input-->
                    <div class="form-floating mb-3">
                        <textarea class="form-control" id="message" type="text" placeholder="Enter your message here..." style="height: 10rem" data-sb-validations="required"></textarea>
                        <label for="message">Message</label>
                        <div class="invalid-feedback" data-sb-feedback="message:required">A message is required.</div>
                    </div>
                    <!-- Submit success message-->
                    <!---->
                    <!-- This is what your users will see when the form-->
                    <!-- has successfully submitted-->
                    <div class="d-none" id="submitSuccessMessage">
                        <div class="text-center mb-3">
                            <div class="fw-bolder">Form submission successful!</div>
                            To activate this form, sign up at
                            <br/>
                            <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                        </div>
                    </div>
                    <!-- Submit error message-->
                    <!---->
                    <!-- This is what your users will see when there is-->
                    <!-- an error submitting the form-->
                    <div class="d-none" id="submitErrorMessage">
                        <div class="text-center text-danger mb-3">Error sending message!</div>
                    </div>
                    <!-- Submit Button-->
                    <button class="btn btn-primary btn-xl disabled" id="submitButton" type="submit">Send</button>
                </form>
            </div>
        </div>
    </div>
</section>

Freelancer/Views/Partials/grid/editors/base.cshtml
@model dynamic

@try
{
    string editor = EditorView(Model);
    <text>@await Html.PartialAsync(editor, Model as object)</text>
}
catch (Exception ex)
{
    <pre>@ex.ToString()</pre>
}

@functions{

    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.Replace(".html", ".cshtml");

        if (!view.Contains("/"))
        {
            view = "grid/editors/" + view;
        }

        return view;
    }
}

Freelancer/Views/Partials/grid/editors/embed.cshtml
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<dynamic>

@if (Model is not null)
{
  string embedValue = Convert.ToString(Model.value);
  embedValue = embedValue.DetectIsJson() ? Model.value.preview : Model.value;

  <div class="video-wrapper">
    @Html.Raw(embedValue)
  </div>
}